# Generated by Django 2.1 on 2019-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190325_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_stock', models.TextField(default=[])),
            ],
        ),
    ]
