# Generated by Django 2.1 on 2019-03-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190326_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshi',
            name='focus_stock',
            field=models.TextField(default=[]),
        ),
    ]
